"""
app/services/news_engine.py

Fetches intelligence from the Supabase `intelligence_feed` table.
Falls back to contextual generated content if the table is empty or unreachable.

Supabase table schema (run this once in your Supabase SQL editor):
────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS intelligence_feed (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        TEXT NOT NULL,
    source       TEXT NOT NULL,
    date_label   TEXT NOT NULL,          -- e.g. "Today", "2 days ago"
    type         TEXT NOT NULL,          -- NEWS | ACADEMIC | URGENT | SCHOLARSHIP | BLOG
    description  TEXT NOT NULL,
    url          TEXT DEFAULT '',
    college_code TEXT DEFAULT '',        -- blank = central (DSE-wide)
    pinned       BOOLEAN DEFAULT FALSE,
    created_at   TIMESTAMPTZ DEFAULT now()
);
────────────────────────────────────────────────────────────────────
"""
import os
from datetime import datetime

try:
    from supabase import create_client
    _url = os.getenv("SUPABASE_URL", "")
    _key = os.getenv("SUPABASE_KEY", "")
    _sb  = create_client(_url, _key) if _url and _key else None
except Exception:
    _sb = None


class NewsEngine:

    # ------------------------------------------------------------------
    # Public interface
    # ------------------------------------------------------------------

    @classmethod
    def generate_intelligence(cls, college_name: str, exam_type: str = "DSE") -> dict:
        """
        Returns dict:
          { campus: [...], central: [...], timestamp: ISO-string }
        Campus items  → rows with matching college_name OR all if college_name is 'General'
        Central items → rows with empty college_code (DSE-wide news)
        """
        now = datetime.now()

        campus_items  = cls._fetch_college_news(college_name)
        central_items = cls._fetch_central_news()

        # If database has nothing yet, use contextual fallback
        if not campus_items:
            campus_items = cls._fallback_campus(college_name)
        if not central_items:
            central_items = cls._fallback_central()

        return {
            "campus":    campus_items[:6],
            "central":   central_items[:6],
            "timestamp": now.isoformat()
        }

    # ------------------------------------------------------------------
    # Supabase fetchers
    # ------------------------------------------------------------------

    @classmethod
    def _fetch_college_news(cls, college_name: str) -> list:
        if not _sb:
            return []
        try:
            query = _sb.table("intelligence_feed") \
                .select("*") \
                .neq("college_code", "") \
                .order("pinned", desc=True) \
                .order("created_at", desc=True) \
                .limit(10)

            # If a specific college is requested, try to match it
            if college_name and college_name.lower() != "general":
                first_word = college_name.split()[0]
                # Use ilike for partial match on title/description
                result = _sb.table("intelligence_feed") \
                    .select("*") \
                    .ilike("title", f"%{first_word}%") \
                    .order("created_at", desc=True) \
                    .limit(6) \
                    .execute()
                if result.data:
                    return cls._format_rows(result.data)

            result = query.execute()
            return cls._format_rows(result.data or [])
        except Exception as e:
            print(f"[NewsEngine] college fetch error: {e}")
            return []

    @classmethod
    def _fetch_central_news(cls) -> list:
        if not _sb:
            return []
        try:
            result = _sb.table("intelligence_feed") \
                .select("*") \
                .eq("college_code", "") \
                .order("pinned", desc=True) \
                .order("created_at", desc=True) \
                .limit(10) \
                .execute()
            return cls._format_rows(result.data or [])
        except Exception as e:
            print(f"[NewsEngine] central fetch error: {e}")
            return []

    @staticmethod
    def _format_rows(rows: list) -> list:
        return [
            {
                "title":  r.get("title", ""),
                "source": r.get("source", ""),
                "date":   r.get("date_label", ""),
                "type":   r.get("type", "NEWS"),
                "desc":   r.get("description", ""),
                "url":    r.get("url", ""),
            }
            for r in rows
        ]

    # ------------------------------------------------------------------
    # Fallback content (used when the database table is empty)
    # ------------------------------------------------------------------

    @staticmethod
    def _fallback_campus(college_name: str) -> list:
        # Reduced mock content to avoid misleading users in production
        return [
            {
                "title":  f"Information Request: {college_name}",
                "source": "Ikigai System",
                "date":   "System",
                "type":   "ACADEMIC",
                "desc":   f"We are currently verifying the latest specific updates for {college_name}. Check the official website for real-time circulars.",
                "url":    "",
            }
        ]

    @staticmethod
    def _fallback_central() -> list:
        return [
            {
                "title":  "Official DTE/CET Portal Links",
                "source": "Government",
                "date":   "Always Available",
                "type":   "URGENT",
                "desc":   "Please refer to the official CET Cell website for the most accurate and up-to-date admission schedules and merit lists.",
                "url":    "https://fe2024.mahacet.org",
            }
        ]
