import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { College } from '../types/college';
import type { UserProfile } from '../types/user';

/**
 * EXPORT_UTILS.ts — Utility functions for PDF and CSV generation with AI Insights
 */

export const exportToCSV = (colleges: College[], filename: string = 'ikigai-predictions.csv') => {
  if (!colleges.length) return;

  const headers = ['College Name', 'Branch', 'City', 'Cutoff Rank', 'Admission Chance', 'Fit Category', 'Fees'];
  const rows = colleges.map(c => [
    `"${c.college_name}"`,
    `"${c.branch}"`,
    `"${c.city}"`,
    c.cutoff_rank || 0,
    c.admission_chance || c.admission_chance_percentage || 'N/A',
    c.probability_level || c.fit || 'N/A',
    c.fees || 0
  ]);

  const csvContent = [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('download', filename);
  link.style.visibility = 'hidden';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};

export const exportToPDF = (
  colleges: College[], 
  profile: UserProfile | null, 
  aiInsights: string = '',
  filename: string = 'ikigai-report.pdf'
) => {
  if (!colleges.length) return;

  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 14;

  // Header Background
  doc.setFillColor(79, 70, 229); // Indigo 600
  doc.rect(0, 0, pageWidth, 45, 'F');

  // Title
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(24);
  doc.text("IKIGAI ADMISSION REPORT", margin, 25);
  
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("Generated by Ikigai AI Analysis Engine", margin, 35);

  // User details section
  doc.setTextColor(50, 50, 50);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("CANDIDATE PROFILE", margin, 60);
  
  doc.setLineWidth(0.5);
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, 62, pageWidth - margin, 62);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  const profileY = 70;
  doc.text(`Name: ${profile?.name || 'Student'}`, margin, profileY);
  doc.text(`Exam: ${profile?.exam_type || 'CET'}`, margin, profileY + 7);
  doc.text(`Rank: ${profile?.exam_type === 'CET' ? profile?.cet_rank : profile?.diploma_rank || 'N/A'}`, pageWidth / 2, profileY);
  doc.text(`Score: ${profile?.exam_type === 'CET' ? profile?.cet_score : profile?.diploma_score || 'N/A'}%`, pageWidth / 2, profileY + 7);

  // AI Insights Section
  let currentY = 95;
  if (aiInsights) {
    doc.setFillColor(243, 244, 246); // Gray 100
    doc.roundedRect(margin, currentY, pageWidth - (margin * 2), 30, 3, 3, 'F');
    
    doc.setTextColor(79, 70, 229); // Indigo 600
    doc.setFont("helvetica", "bold");
    doc.text("AI STRATEGIC INSIGHTS", margin + 5, currentY + 10);
    
    doc.setTextColor(70, 70, 70);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    const splitText = doc.splitTextToSize(aiInsights, pageWidth - (margin * 2) - 10);
    doc.text(splitText, margin + 5, currentY + 18);
    currentY += 45;
  }

  // Table
  doc.setTextColor(50, 50, 50);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("PREDICTION ANALYSIS", margin, currentY);
  currentY += 5;

  const tableData = colleges.slice(0, 50).map((c, i) => [
    (i + 1).toString(),
    c.college_name || 'N/A',
    c.branch || 'N/A',
    c.city || 'N/A',
    c.cutoff_rank ? c.cutoff_rank.toString() : 'N/A',
    c.probability_level || c.fit || 'N/A',
    `${c.admission_chance || c.admission_chance_percentage || 'N/A'}%`
  ]);

  autoTable(doc, {
    startY: currentY,
    head: [['#', 'College Name', 'Branch', 'City', 'Rank', 'Fit', 'Chance']],
    body: tableData,
    theme: 'striped',
    headStyles: { fillColor: [79, 70, 229], textColor: 255 },
    styles: { fontSize: 8, cellPadding: 2 },
    columnStyles: {
      0: { cellWidth: 8 },
      1: { cellWidth: 60 },
      2: { cellWidth: 40 },
      3: { cellWidth: 25 },
      4: { cellWidth: 15 },
      5: { cellWidth: 22 },
      6: { cellWidth: 15 }
    }
  });

  // Footer on each page
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Page ${i} of ${pageCount} | Generated by Ikigai Smart Analysis | ${new Date().toLocaleDateString()}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
  }

  doc.save(filename);
};

export const exportDreamList = (
  colleges: College[], 
  profile: any, 
  filename: string = 'ikigai-dream-list.pdf'
) => {
  if (!colleges.length) return;

  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 14;

  // Premium Dream Header
  doc.setFillColor(30, 41, 59); // Slate 800
  doc.rect(0, 0, pageWidth, 40, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("DREAM COLLEGE STRATEGY", margin, 22);
  
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text("Strategic targets based on competitive proximity | Exact -> Nearly -> Risk", margin, 32);

  // Profile
  doc.setTextColor(50, 50, 50);
  doc.setFontSize(10);
  doc.text(`Student: ${profile?.name || 'Candidate'}`, margin, 50);
  doc.text(`Rank: ${profile?.exam_type === 'CET' ? profile?.cet_rank : profile?.diploma_rank || 'N/A'}`, pageWidth - 60, 50);

  const tableData = colleges.map((c) => [
    c.college_code,
    c.college_name,
    c.branch || 'N/A',
    c.city || 'N/A',
    profile?.exam_type === 'CET' ? profile?.cet_rank : profile?.diploma_rank || 'N/A',
    c.cutoff_rank || 'N/A',
    c.fit || 'Unknown',
    `${c.admission_chance || 'N/A'}%`,
    c.available_branches?.slice(0, 3).join(', ') || 'N/A'
  ]);

  autoTable(doc, {
    startY: 60,
    head: [['Code', 'College', 'Branch', 'City', 'Your Rank', 'Cutoff', 'Fit', 'Chance', 'Available Branches']],
    body: tableData,
    theme: 'grid',
    headStyles: { fillColor: [79, 70, 229], textColor: 255 },
    styles: { fontSize: 7, cellPadding: 2 },
    columnStyles: {
      0: { cellWidth: 12 },
      1: { cellWidth: 40 },
      2: { cellWidth: 30 },
      3: { cellWidth: 20 },
      4: { cellWidth: 15 },
      5: { cellWidth: 15 },
      6: { cellWidth: 18 },
      7: { cellWidth: 12 },
      8: { cellWidth: 30 }
    }
  });

  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(`Dream List | Ikigai Intelligence | Page ${i}`, pageWidth/2, doc.internal.pageSize.getHeight() - 10, { align: 'center' });
  }

  doc.save(filename);
};

export const exportDreamCSV = (
  colleges: College[], 
  profile: any, 
  filename: string = 'ikigai-dream-list.csv'
) => {
  if (!colleges.length) return;

  const headers = [
    'College Code', 'College Name', 'Branch', 'City', 
    'Your Rank', 'Cutoff Rank', 'Fit Category', 'Admission Chance', 
    'Other Available Branches'
  ];

  const rows = colleges.map(c => [
    `"${c.college_code}"`,
    `"${c.college_name}"`,
    `"${c.branch || 'N/A'}"`,
    `"${c.city || 'N/A'}"`,
    profile?.exam_type === 'CET' ? profile?.cet_rank : profile?.diploma_rank || 'N/A',
    c.cutoff_rank || 0,
    `"${c.fit || 'Unknown'}"`,
    `"${c.admission_chance || 0}%"`,
    `"${c.available_branches?.slice(0, 5).join(', ') || ''}"`
  ]);

  const csvContent = [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('download', filename);
  link.style.visibility = 'hidden';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};

export const exportStrategicForm = (
  colleges: College[], 
  profile: any, 
  filename: string = 'ikigai-strategic-option-form.pdf'
) => {
  if (!colleges.length) return;

  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 14;

  // Expert Header
  doc.setFillColor(88, 28, 135); // Purple 900
  doc.rect(0, 0, pageWidth, 45, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(24);
  doc.text("EXPERT OPTION FORM", margin, 25);
  
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("Balanced Strategy: 5% Ambition | 55% Target | 40% Backup", margin, 35);

  // Profile Info
  doc.setTextColor(50, 50, 50);
  doc.setFontSize(10);
  doc.text(`Candidate: ${profile?.name || 'Student'}`, margin, 55);
  doc.text(`Rank: ${profile?.cet_rank || profile?.diploma_rank || 'N/A'}`, pageWidth - 60, 55);

  const tableData = colleges.map((c, index) => [
    index + 1,
    c.college_code,
    c.college_name,
    c.branch || 'N/A',
    c.fit || 'N/A',
    `${c.admission_chance || 'N/A'}%`,
    c.display_fees || 'N/A'
  ]);

  autoTable(doc, {
    startY: 65,
    head: [['Sr.', 'Code', 'College Name', 'Branch', 'Categorization', 'Success Prob.', 'Fees']],
    body: tableData,
    theme: 'striped',
    headStyles: { fillColor: [107, 33, 168], textColor: 255 },
    styles: { fontSize: 8 },
    columnStyles: {
      0: { cellWidth: 10 },
      1: { cellWidth: 20 },
      2: { cellWidth: 60 },
      3: { cellWidth: 40 },
      4: { cellWidth: 25 },
      5: { cellWidth: 20 }
    }
  });

  // Add Advisory Footer
  const finalY = (doc as any).lastAutoTable.finalY + 15;
  doc.setFont("helvetica", "italic");
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  doc.text("Advisory: This list is generated using AI predictive modeling based on historical trends.", margin, finalY);
  doc.text("Please verify all college codes before final submission on the official portal.", margin, finalY + 5);

  doc.save(filename);
};

export const exportDetailedCollegeReport = (
  college: College,
  insights: string,
  profile: any,
  filename: string = 'detailed-college-report.pdf'
) => {
  if (!college) return;
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 14;

  /** PAGE 1: STRATEGIC SUMMARY & BRANDING **/
  // Branded Header
  doc.setFillColor(15, 23, 42); // Slate 900
  doc.rect(0, 0, pageWidth, 60, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text(college.college_name.toUpperCase(), margin, 25, { maxWidth: pageWidth - 40 });
  
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`${college.city}, MS | Estd. ${college.established_year || '1960'} | ${college.accreditation || 'NAAC Accredited'}`, margin, 45);
  doc.text(`Strategic Admission Profile for Rank: ${profile?.cet_rank || profile?.diploma_rank}`, margin, 52);

  // Strategic Verdict Area
  doc.setTextColor(51, 65, 85); 
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("1. STRATEGIC POSITIONING", margin, 80);
  doc.setDrawColor(99, 102, 241);
  doc.line(margin, 83, margin + 40, 83);

  const verdictLine = insights.split('\n').find(l => l.includes('Verdict:')) || "Verdict: Best Fit";
  const probabilityLine = insights.split('\n').find(l => l.includes('Probability')) || "85% Probability";

  doc.setFontSize(12);
  doc.setTextColor(79, 70, 229); // Indigo
  doc.text(verdictLine.replace(/\*\*/g, ''), margin, 95);
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(probabilityLine.replace(/\*\*/g, ''), margin, 102);

  // Performance Table
  autoTable(doc, {
    startY: 110,
    head: [['Key Performance Metric', 'Data Point']],
    body: [
      ['Placement Rate', `${college.placement_rate || 0}%`],
      ['Average Package', `INR ${college.average_package_lpa || 0} LPA`],
      ['Highest Package', `INR ${college.highest_package_lpa || 0} LPA`],
      ['Campus Reputation', college.accreditation || 'Excellent'],
      ['Student ROI', (college.placement_rate || 0) > 80 ? 'HIGH' : 'MODERATE']
    ],
    theme: 'striped',
    headStyles: { fillColor: [15, 23, 42] }
  });

  doc.setFontSize(9);
  doc.setTextColor(150, 150, 150);
  doc.text("- Page 1: Strategic Admission Overview -", pageWidth / 2, pageHeight - 10, { align: 'center' });

  /** PAGE 2: ADMISSION & ACADEMIC INTELLIGENCE **/
  doc.addPage();
  doc.setFillColor(248, 250, 252);
  doc.rect(0, 0, pageWidth, 40, 'F');
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(16);
  doc.text("ADMISSION & ACADEMIC INTELLIGENCE", margin, 25);

  doc.setFontSize(14);
  doc.text("2. CUTOFF & SEAT MATRIX ANALYSIS", margin, 55);
  doc.line(margin, 57, margin + 30, 57);

  autoTable(doc, {
    startY: 65,
    head: [['Academic Stream', 'Matrix Category', 'Intake', 'Prev Rank']],
    body: [
      [college.branch_name || 'Stream A', 'GOPEN', college.seats || 60, college.cutoff_rank || 'N/A'],
      [college.branch_name || 'Stream A', 'LOPEN', 'N/A', 'N/A'],
      [college.branch_name || 'Stream A', 'DEF/PH', 'N/A', 'N/A']
    ],
    theme: 'grid'
  });

  doc.setFontSize(14);
  doc.text("3. FEE EXPOSITION", margin, (doc as any).lastAutoTable.finalY + 15);
  
  autoTable(doc, {
    startY: (doc as any).lastAutoTable.finalY + 22,
    head: [['Category Breakdown', 'Annual Fees (INR)']],
    body: [
      ['OPEN / General', `INR ${college.fees || '0'}`],
      ['OBC / EBC (50%)', `INR ${(college.fees || 0) / 2}`],
      ['SC / ST (Free-ship)', 'INR 0 (Excluded Exams)'],
      ['TFWS / EWS', `INR ${(college.fees || 0) * 0.1}`]
    ],
    theme: 'striped'
  });

  doc.setFontSize(14);
  doc.text("4. MANDATORY DOCUMENT CHECKLIST", margin, (doc as any).lastAutoTable.finalY + 15);
  const docs = ["SSC/HSC Marksheets", "CET/JEE Scorecard", "LC/TC Transfer", "Domicile Certificate", "Income Certificate"];
  doc.setFontSize(10);
  docs.forEach((d, i) => {
    doc.text(`[ ] ${d}`, margin + 5, (doc as any).lastAutoTable.finalY + 25 + (i * 7));
  });

  doc.text("- Page 2: Academic & Financial Analysis -", pageWidth / 2, pageHeight - 10, { align: 'center' });

  /** PAGE 3: DEEP-DIVE AI INSIGHTS & CAREER **/
  doc.addPage();
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, pageWidth, 30, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.text("DEEP-DIVE AI ANALYSIS & CAREER OUTLOOK", margin, 20);

  doc.setTextColor(15, 23, 42);
  doc.setFontSize(14);
  doc.text("5. PROFESSIONAL AI BRIEFING", margin, 50);
  doc.line(margin, 52, margin + 35, 52);

  doc.setFontSize(10);
  const cleanInsights = insights
    .replace(/### /g, '')
    .replace(/\*\*/g, '')
    .split('\n')
    .filter(line => line.trim() !== '' && !line.includes('Verdict'));

  const splitInsights = doc.splitTextToSize(cleanInsights.join('\n\n'), pageWidth - 28);
  doc.text(splitInsights, margin, 65);

  const insightsY = 65 + (splitInsights.length * 5.5);

  doc.setFontSize(14);
  doc.text("6. TOP RECRUITING PARTNERS", margin, insightsY + 15);
  const recruiters = college.top_recruiters?.split(',') || ['TCS', 'Infosys', 'Wipro', 'Accenture', 'Cognizant', 'Capgemini'];
  
  autoTable(doc, {
    startY: insightsY + 22,
    body: [
        recruiters.slice(0, 3),
        recruiters.slice(3, 6)
    ],
    theme: 'plain',
    styles: { cellPadding: 5, fontSize: 10, fontStyle: 'bold' }
  });

  // Footer Disclaimer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("This report is generated using Ikigai AI Scraping and Simulation Engine.", margin, pageHeight - 25);
  doc.text("Historical data trends are used to simulate academic and placement environment.", margin, pageHeight - 20);

  doc.setFontSize(9);
  doc.text("- Page 3: Professional Insights & Advisory -", pageWidth / 2, pageHeight - 10, { align: 'center' });

  doc.save(filename || `${college.college_code}-Detailed-Report.pdf`);
};

