"""
app/services/news_engine.py

Fetches intelligence from the Supabase `intelligence_feed` table.
Falls back to contextual generated content if the table is empty or unreachable.

Supabase table schema (run this once in your Supabase SQL editor):
────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS intelligence_feed (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        TEXT NOT NULL,
    source       TEXT NOT NULL,
    date_label   TEXT NOT NULL,          -- e.g. "Today", "2 days ago"
    type         TEXT NOT NULL,          -- NEWS | ACADEMIC | URGENT | SCHOLARSHIP | BLOG
    description  TEXT NOT NULL,
    url          TEXT DEFAULT '',
    college_code TEXT DEFAULT '',        -- blank = central (DSE-wide)
    pinned       BOOLEAN DEFAULT FALSE,
    created_at   TIMESTAMPTZ DEFAULT now()
);
────────────────────────────────────────────────────────────────────
"""
import os
from datetime import datetime

try:
    from supabase import create_client
    _url = os.getenv("SUPABASE_URL", "")
    _key = os.getenv("SUPABASE_KEY", "")
    _sb  = create_client(_url, _key) if _url and _key else None
except Exception:
    _sb = None


class NewsEngine:

    # ------------------------------------------------------------------
    # Public interface
    # ------------------------------------------------------------------

    @classmethod
    def generate_intelligence(cls, college_name: str, exam_type: str = "DSE") -> dict:
        """
        Returns dict:
          { campus: [...], central: [...], timestamp: ISO-string }
        Campus items  → rows with matching college_name OR all if college_name is 'General'
        Central items → rows with empty college_code (DSE-wide news)
        """
        now = datetime.now()

        campus_items  = cls._fetch_college_news(college_name)
        central_items = cls._fetch_central_news()

        # If database has nothing yet, use contextual fallback
        if not campus_items:
            campus_items = cls._fallback_campus(college_name)
        if not central_items:
            central_items = cls._fallback_central()

        return {
            "campus":    campus_items[:6],
            "central":   central_items[:6],
            "timestamp": now.isoformat()
        }

    # ------------------------------------------------------------------
    # Supabase fetchers
    # ------------------------------------------------------------------

    @classmethod
    def _fetch_college_news(cls, college_name: str) -> list:
        if not _sb:
            return []
        try:
            query = _sb.table("intelligence_feed") \
                .select("*") \
                .neq("college_code", "") \
                .order("pinned", desc=True) \
                .order("created_at", desc=True) \
                .limit(10)

            # If a specific college is requested, try to match it
            if college_name and college_name.lower() != "general":
                first_word = college_name.split()[0]
                # Use ilike for partial match on title/description
                result = _sb.table("intelligence_feed") \
                    .select("*") \
                    .ilike("title", f"%{first_word}%") \
                    .order("created_at", desc=True) \
                    .limit(6) \
                    .execute()
                if result.data:
                    return cls._format_rows(result.data)

            result = query.execute()
            return cls._format_rows(result.data or [])
        except Exception as e:
            print(f"[NewsEngine] college fetch error: {e}")
            return []

    @classmethod
    def _fetch_central_news(cls) -> list:
        if not _sb:
            return []
        try:
            result = _sb.table("intelligence_feed") \
                .select("*") \
                .eq("college_code", "") \
                .order("pinned", desc=True) \
                .order("created_at", desc=True) \
                .limit(10) \
                .execute()
            return cls._format_rows(result.data or [])
        except Exception as e:
            print(f"[NewsEngine] central fetch error: {e}")
            return []

    @staticmethod
    def _format_rows(rows: list) -> list:
        return [
            {
                "title":  r.get("title", ""),
                "source": r.get("source", ""),
                "date":   r.get("date_label", ""),
                "type":   r.get("type", "NEWS"),
                "desc":   r.get("description", ""),
                "url":    r.get("url", ""),
            }
            for r in rows
        ]

    # ------------------------------------------------------------------
    # Fallback content (used when the database table is empty)
    # ------------------------------------------------------------------

    @staticmethod
    def _fallback_campus(college_name: str) -> list:
        first = college_name.split()[0] if college_name and college_name != "General" else "College"
        return [
            {
                "title":  f"Direct Second Year Admission — Orientation at {first}",
                "source": "Academic Office",
                "date":   "Today",
                "type":   "ACADEMIC",
                "desc":   f"Mandatory orientation for new DSE batch. Original documents required: Diploma Marksheets, LC, Category Certificate.",
                "url":    "https://dte.maharashtra.gov.in",
            },
            {
                "title":  f"Industry Lab Inauguration at {first}",
                "source": "Campus Press",
                "date":   "3 days ago",
                "type":   "NEWS",
                "desc":   f"The institute inaugurates a state-of-the-art lab for emerging technology domains, expanding research infrastructure for students.",
                "url":    "",
            },
            {
                "title":  f"Placement Drive Update — {first} Engineering",
                "source": "Training & Placement Cell",
                "date":   "1 week ago",
                "type":   "BLOG",
                "desc":   "Campus recruitment drive for the 2024 batch is underway. Students are advised to complete their resume verification before reporting.",
                "url":    "",
            },
        ]

    @staticmethod
    def _fallback_central() -> list:
        return [
            {
                "title":  "DTE Maharashtra: DSE 2025 Provisional Merit List Released",
                "source": "CET Cell Official",
                "date":   "Real-Time",
                "type":   "URGENT",
                "desc":   "The Provisional Merit List for Direct Second Year Engineering (DSE) has been published on the official DTE portal. Check your rank now.",
                "url":    "https://fe2024.mahacet.org",
            },
            {
                "title":  "Bridge Course in Mathematics — Mandatory for Diploma Students",
                "source": "MSBTE / DTE Circular",
                "date":   "2 days ago",
                "type":   "ACADEMIC",
                "desc":   "All diploma students joining second-year degree programs must complete a bridge course in Engineering Mathematics as per SPPU/RTMNU norms.",
                "url":    "https://dte.maharashtra.gov.in",
            },
            {
                "title":  "MahaDBT Scholarship: Last Date for Fee Reimbursement Application",
                "source": "MahaDBT Portal",
                "date":   "4 days ago",
                "type":   "SCHOLARSHIP",
                "desc":   "EBC, OBC, SC/ST students must apply for fee reimbursement on mahadbt.maharashtra.gov.in before the deadline. Original fee receipt required.",
                "url":    "https://mahadbt.maharashtra.gov.in",
            },
            {
                "title":  "CAP Round 1 Allotment Result — Check Your Seat",
                "source": "CET Cell Portal",
                "date":   "5 days ago",
                "type":   "URGENT",
                "desc":   "Round 1 seat allotment results are live. Log in to the portal to view your allotted institute. Report to the college by the deadline to confirm admission.",
                "url":    "https://fe2024.mahacet.org",
            },
        ]
